name: Deploy githubtestsolution

on:
  workflow_run:
    workflows: ["Pack githubtestsolution"]
    branches: [main]
    types:
      - completed
  workflow_dispatch:

jobs:
  deploy:
    runs-on: windows-latest
    environment: Test
    steps:
      - uses: dawidd6/action-download-artifact@v3
        with:
          workflow: pack-solution.yml
          name: packed-solution
      - uses: microsoft/powerplatform-actions/import-solution@v0
        with:
          environment-url: https://org09835e11.crm.dynamics.com
          user-name: ${{ secrets.TESTENV }}
          solution-file: githubtestsolution_managed.zip
