name: Deploy githubtestsolution

on:
  workflow_run:
    workflows: ["Pack githubtestsolution"]
    branches: [main]
    types:
      - completed
  workflow_dispatch:

jobs:
  deploy:
    runs-on: windows-latest
    environment: Test
    steps:
      - uses: dawidd6/action-download-artifact@v3
        with:
          workflow: pack-solution.yml
          name: packed-solution
      - uses: microsoft/powerplatform-actions/import-solution@v0
        with:
          environment-url: https://org09835e11.crm.dynamics.com
          user-name: TESTENV
          app-id:  e18d5d2a-26f6-4a2c-b24e-a9631a7b96f1
          client-secret: 9.r8Q~SZ-.v2qSFiDuBauPCho3jvcVTZk4B.8a6m
          tenant-id: 817a3ad3-0cc9-43e1-acbd-70706f0d7c10
          solution-file: githubtestsolution_managed.zip
